/**
 * Conteúdo das páginas de detalhe dos projetos.
 *
 * Esta é a fonte da verdade: edite aqui e rode `node scripts/generate_project_pages.js`
 * para regenerar os arquivos em `projetos/`.
 *
 * O texto foi destilado dos dossiês técnicos em `readme/` (não versionados),
 * mantendo deliberadamente a seção "limites" — descrever com precisão o que o
 * projeto NÃO faz vale mais em entrevista do que exagerar o que ele faz.
 */

module.exports = [
    // ===== Projetos principais (também aparecem em destaque na home) =====
    {
        slug: 'torre-logistica',
        title: 'Torre Logística',
        subtitle: 'Operação logística em tempo real',
        badge: 'No ar · release v1.0.1',
        image: '../assets/projetos/torre-logistica-console-painel.webp',
        imageSize: [1568, 560],
        video: {
            src: '../assets/projetos/torre-logistica-demo.mp4',
            poster: '../assets/projetos/torre-logistica-poster.jpg',
            caption: 'Passeio de 33 s pela demo pública: console, PWA do motorista e rastreamento.',
        },
        gallery: [
            { src: '../assets/projetos/torre-logistica-console-painel.webp', w: 1568, h: 560, alt: 'Painel operacional do console: contadores por estado e alertas abertos com a evidência de cada um.', caption: 'Console operacional: alertas com evidência' },
            { src: '../assets/projetos/torre-logistica-pwa-motorista.webp', w: 516, h: 734, alt: 'PWA do motorista: rota do dia com a próxima entrega em destaque e o botão Abrir entrega.', caption: 'PWA do motorista, offline-first' },
            { src: '../assets/projetos/torre-logistica-rastreamento-publico.webp', w: 649, h: 783, alt: 'Rastreamento público: status A caminho, entrega prevista, chegada estimada e linha do tempo.', caption: 'Rastreamento público do destinatário' },
        ],
        repo: 'https://github.com/Lucasantunesribeiro/torre-logistica',
        demo: 'https://operacao.torre.lucasafvr.com.br',
        links: [
            { label: 'Release v1.0.1', icon: 'fas fa-tag', url: 'https://github.com/Lucasantunesribeiro/torre-logistica/releases/tag/v1.0.1' },
            { label: 'Relatório de pentest', icon: 'fas fa-shield-halved', url: 'https://github.com/Lucasantunesribeiro/torre-logistica/blob/main/docs/pentest-v1.md' },
        ],
        tags: ['.NET 10', 'ASP.NET Core', 'PostgreSQL 17', 'PostGIS', 'EF Core 10', 'SignalR', 'React 19', 'TypeScript', 'Docker', 'GitHub Actions'],
        facts: [
            { label: 'Arquitetura', value: 'Monólito modular com Workers separados' },
            { label: 'Testes', value: '1.392 · 695 unidade, 544 integração com PostGIS real, 131 frontend, 22 arquitetura' },
            { label: 'Segurança', value: 'Pentest gray-box em produção: 16 categorias, sem vulnerabilidade alta' },
            { label: 'Infra da demo', value: 'VM Always Free (Oracle Cloud) · US$ 0,00/mês' },
        ],
        overview: [
            'Plataforma B2B de operação logística em tempo real: acompanha cada entrega entre a saída para rota e a conclusão, com localização, ETA, SLA, geofencing, alertas, ocorrências, prova de entrega e rastreamento público controlado.',
            'São três experiências sobre o mesmo núcleo: o <strong>console</strong> para administrador, supervisor e operador; a <strong>PWA do motorista</strong>, que funciona offline; e a página de <strong>rastreamento</strong> do destinatário, com token forte e sem dados sensíveis. Não é um SaaS comercial ativo: é um projeto de portfólio arquitetado para virar um sem reescrita.',
        ],
        architecture: {
            summary: 'Monólito modular em .NET 10 com um processo de Workers separado, três aplicações React e PostgreSQL com PostGIS. O simulador é um cliente externo, sem acesso ao núcleo. Decisões registradas em 35 ADRs, cada uma com a forma de verificá-la.',
            layers: [
                { name: 'TorreLogistica.Domain', desc: 'Regras e invariantes, sem infraestrutura.' },
                { name: 'TorreLogistica.Application', desc: 'Casos de uso; usa o EF Core direto, sem repositório (ADR 0008).' },
                { name: 'TorreLogistica.Infrastructure', desc: 'PostgreSQL/PostGIS, relógio e gerador de identificador.' },
                { name: 'TorreLogistica.Api', desc: 'Borda HTTP e SignalR.' },
                { name: 'TorreLogistica.Workers', desc: 'Carga assíncrona: SLA, webhooks e limpeza de rastro vencido.' },
                { name: 'TorreLogistica.Simulator', desc: 'Cliente externo que encena seis histórias contra a API real.' },
                { name: 'apps/', desc: 'Três aplicações web: console operacional, PWA do motorista e rastreamento público.' },
            ],
        },
        flow: {
            title: 'Ciclo de uma entrega',
            steps: [
                'A entrega é criada, planejada e atribuída a um motorista.',
                'O motorista sai para a rota. Cada ação nasce no aparelho com identificador próprio e fica guardada se não houver conexão.',
                'A ingestão grava a posição, avalia o <strong>geofence</strong> do destino no PostGIS (com histerese) e recalcula ETA e SLA fora da requisição.',
                'O console recebe o aviso em tempo real por <strong>SignalR</strong>, só depois do commit; o motor de alertas abre, deduplica e reabre alertas por regra tipada.',
                'Ocorrências entram como registros somente-inserção, com motivo tipado; falha de entrega vira tentativa frustrada e reagendamento.',
                'Na chegada, a prova de entrega sobe direto ao storage por <strong>URL assinada</strong> de curta duração; a entrega é concluída e o histórico fica na timeline numerada.',
            ],
        },
        highlights: [
            '<strong>Geofence e ETA no PostGIS:</strong> chegada detectada na ingestão da posição, com histerese contra oscilação de GPS; ETA e SLA explicáveis, sem IA.',
            '<strong>Tempo real com SignalR:</strong> o console recebe o aviso só depois do commit; alertas são regras tipadas que carregam a evidência.',
            '<strong>PWA offline-first:</strong> toda ação é aplicada exatamente uma vez ao reconectar, com o registro da operação na mesma transação do efeito.',
            '<strong>Prova de entrega e rastreamento seguros:</strong> foto por URL assinada de curta duração; link público com token forte (o banco guarda só o hash) e posição aproximada.',
            '<strong>Multi-tenancy e RBAC:</strong> filtro por organização que falha fechado; Transactional Outbox nos webhooks.',
            '<strong>Contrato testado contra a API real:</strong> o CI barra descompasso entre frontend e backend.',
            '<strong>Números medidos, não estimados:</strong> a ingestão sustentou 32,7 posições por segundo (meta de 33) em ambiente local, e o particionamento da tabela de posições foi recusado porque a medição não o justificou.',
        ],
        limits: [
            'A demo pública roda numa VM Always Free de 1 GB, nó único e sem SLA. A arquitetura de produção no Azure foi aplicada e depois destruída por decisão de custo.',
            'O ETA é determinístico e explicável, não preditivo: decisão registrada no ADR 0018.',
            'O dado de demonstração é fictício e determinístico: mesma semente, mesma história.',
            'Fora do escopo: billing, roteirização ótima (VRP), app nativo, chat e emissão fiscal.',
            'Há uma única instância da API: tempo real e alertas pressupõem processo único, e várias instâncias exigiriam um backplane.',
        ],
    },
    {
        slug: 'central-antifraude',
        title: 'Central Antifraude',
        subtitle: 'Sistemas distribuídos e decisão de risco',
        badge: 'No ar · release v1.0.0',
        image: '../assets/projetos/central-antifraude-transacao-explicavel.jpg',
        imageSize: [1568, 751],
        video: {
            src: '../assets/projetos/central-antifraude-demo.mp4',
            poster: '../assets/projetos/central-antifraude-poster.jpg',
            caption: 'Demo de 24 s: painel, fila de alertas, transação explicável e caso de falso positivo.',
        },
        gallery: [
            { src: '../assets/projetos/central-antifraude-transacao-explicavel.jpg', w: 1568, h: 751, alt: 'Transação com score 75 e decisão Bloquear, com os sinais que justificam o score.', caption: 'Score 75 e os sinais que o explicam' },
            { src: '../assets/projetos/central-antifraude-falso-positivo.jpg', w: 1568, h: 751, alt: 'Caso investigado: transação marcada como Revisar e concluída como Legítima, com notas e histórico.', caption: 'Falso positivo: Revisar, concluído como Legítima' },
        ],
        repo: 'https://github.com/Lucasantunesribeiro/central-antifraude',
        demo: 'https://central-antifraude.vercel.app',
        links: [
            { label: 'Release v1.0.0', icon: 'fas fa-tag', url: 'https://github.com/Lucasantunesribeiro/central-antifraude/releases/tag/v1.0.0' },
            { label: 'Relatório de pentest', icon: 'fas fa-shield-halved', url: 'https://github.com/Lucasantunesribeiro/central-antifraude/blob/main/docs/pentest-v1.md' },
        ],
        tags: ['.NET 10', 'ASP.NET Core', 'PostgreSQL 17', 'EF Core', 'AWS Lambda', 'SQS', 'EventBridge', 'React 19', 'TypeScript', 'Neon', 'Vercel'],
        facts: [
            { label: 'Decisão', value: 'Permitir · Revisar · Bloquear, com score determinístico e versionado' },
            { label: 'Testes', value: '1.211 · 546 unidade, 480 integração com PostgreSQL real, 134 frontend, 51 arquitetura' },
            { label: 'Segurança', value: 'Pentest gray-box em produção: 19 vetores, sem achado alto' },
            { label: 'Infra', value: 'Lambda (arm64) + SQS/DLQ + EventBridge · Neon · Vercel · custo esperado US$ 0,00' },
        ],
        overview: [
            'Plataforma B2B para avaliação de risco, monitoramento e investigação de transações suspeitas em pagamentos digitais. Recebe transações de sistemas externos autenticados por credencial própria, avalia o risco de forma determinística e explicável e devolve <strong>Permitir</strong>, <strong>Revisar</strong> ou <strong>Bloquear</strong> com os sinais que justificam a decisão.',
            'A plataforma não processa dinheiro: recomenda uma ação e dá ao analista as ferramentas para investigar o que ficou em dúvida, com fila de alertas, casos com timeline, regras versionadas e backtest antes de publicar. O efeito assíncrono sai por Outbox, fila e Inbox, com efeito único mesmo com entrega repetida.',
        ],
        architecture: {
            summary: 'API .NET 10 em AWS Lambda (Function URL) sobre PostgreSQL no Neon, com frontend na Vercel. O evento de cada avaliação sai por Outbox para uma fila SQS, e um Lambda consumidor aplica os efeitos. A infraestrutura é declarada em AWS SAM e os segredos ficam no SSM Parameter Store, nunca em variável de ambiente.',
            layers: [
                { name: 'CentralAntifraude.Domain', desc: 'Invariantes e primitivos, com zero dependência.' },
                { name: 'CentralAntifraude.Application', desc: 'Contratos e casos de uso.' },
                { name: 'CentralAntifraude.Infrastructure', desc: 'PostgreSQL, EF Core e relógio.' },
                { name: 'CentralAntifraude.Api', desc: 'Composição HTTP com Minimal APIs. Testes de arquitetura seguram a direção das dependências.' },
                { name: 'Lambda despachante', desc: 'Publica a Outbox na fila; é acionado logo após o commit e por uma varredura a cada 15 minutos (EventBridge Scheduler).' },
                { name: 'Lambda consumidor', desc: 'Lê da fila, aplica os efeitos com Inbox na mesma transação e confirma só depois do commit.' },
            ],
        },
        flow: {
            title: 'Caminho de uma transação',
            steps: [
                'O sistema externo envia a tentativa de pagamento com API key própria e chave de idempotência.',
                'Numa única transação <strong>serializável</strong>, a API grava a tentativa, avalia as quatro regras versionadas e grava a avaliação e um evento na Outbox. Conflito refaz a operação inteira; estourado o orçamento de retentativas, responde 503 com <code>Retry-After</code>.',
                'A resposta traz Permitir, Revisar ou Bloquear com score e sinais. Repetir a requisição devolve a avaliação original, sem recalcular.',
                'O despachante publica a Outbox no SQS. A garantia é a tabela; a invocação imediata só reduz a latência.',
                'O consumidor aplica os efeitos (contador diário e alerta) e confirma a mensagem só depois do commit. Falhas repetidas vão para a DLQ após 5 tentativas.',
                'O analista abre um caso a partir do alerta, investiga e conclui. A conclusão humana não reescreve a decisão do motor: um Revisar concluído como Legítima é um falso positivo, não um defeito.',
            ],
        },
        highlights: [
            '<strong>Score explicável e versionado:</strong> quatro regras tipadas; cada decisão guarda a versão do perfil e das regras acionadas, e o banco recusa apagar o que a sustenta.',
            '<strong>Idempotência sob concorrência:</strong> seis requisições simultâneas do mesmo cliente exigem contagens 1 a 6, sem repetir nem pular; repetir a chamada devolve a avaliação original.',
            '<strong>Outbox, SQS e Inbox:</strong> efeito único mesmo com entrega repetida, processo caindo no meio ou vários despachantes ao mesmo tempo.',
            '<strong>Serverless na AWS:</strong> Lambda .NET 10 (arm64), SQS com DLQ, EventBridge Scheduler e segredos no SSM Parameter Store, sem recurso de custo fixo.',
            '<strong>Investigação auditável:</strong> casos com timeline somente-inserção e concorrência otimista; duas resoluções simultâneas produzem exatamente um 200 e um 409.',
            '<strong>Backtest antes de publicar:</strong> reaplica a regra candidata sobre o histórico, no mesmo motor da avaliação real, sem tocar em produção.',
            '<strong>Segurança:</strong> API key própria para integrações, refresh token rotativo, proteção CSRF e rate limit, validados em pentest contra a produção.',
        ],
        limits: [
            'Não processa dinheiro nem guarda PAN, CVV ou credencial financeira: só referências tokenizadas fornecidas por um sistema externo.',
            'Pesos e limiares das regras são configuração de demonstração. As práticas têm fonte (U.S. Payments Forum, ADR 0008); os números não são padrão de mercado.',
            'IA não participa do score, dos sinais nem das explicações: tudo é código determinístico.',
            'Não é banco, gateway, adquirente nem solução certificada de compliance.',
            'A infraestrutura suspende quando ociosa (é o que sustenta o custo zero): a primeira visita depois de um tempo parado leva cerca de 4 s.',
        ],
    },
    {
        slug: 'prisma-rh',
        title: 'Prisma RH',
        subtitle: 'Domínio complexo de folha de pagamento',
        badge: 'No ar · release v1.0.0',
        image: '../assets/projetos/prisma-rh-memoria-de-calculo.jpg',
        imageSize: [1568, 751],
        video: {
            src: '../assets/projetos/prisma-rh-demo.mp4',
            poster: '../assets/projetos/prisma-rh-poster.jpg',
            caption: 'Demo de 29 s: importações, folha mensal, inconsistências e pergunta em português.',
        },
        gallery: [
            { src: '../assets/projetos/prisma-rh-memoria-de-calculo.jpg', w: 1568, h: 751, alt: 'Memória de cálculo do INSS, faixa a faixa, com o teto aplicado e o arredondamento declarado.', caption: 'Memória de cálculo do INSS, faixa a faixa' },
            { src: '../assets/projetos/prisma-rh-inconsistencias.jpg', w: 1568, h: 705, alt: 'Tratamento de inconsistências da folha, com situação, severidade, regra e responsável.', caption: 'Conferência automática e tratamento de inconsistências' },
        ],
        repo: 'https://github.com/Lucasantunesribeiro/prisma_rh',
        demo: 'https://portfolio-prisma-rh.vercel.app',
        links: [
            { label: 'Release v1.0.0', icon: 'fas fa-tag', url: 'https://github.com/Lucasantunesribeiro/prisma_rh/releases/tag/v1.0.0' },
            { label: 'Relatório de pentest', icon: 'fas fa-shield-halved', url: 'https://github.com/Lucasantunesribeiro/prisma_rh/blob/main/docs/seguranca/pentest-2026-09.md' },
        ],
        tags: ['.NET 10', 'ASP.NET Core', 'PostgreSQL 17', 'EF Core', 'AWS Lambda', 'SQS', 'React 19', 'TypeScript', 'Tailwind CSS', 'Neon', 'Vercel'],
        facts: [
            { label: 'Arquitetura', value: 'Monólito modular em quatro camadas; o domínio não referencia EF Core, ASP.NET nem AWS' },
            { label: 'Testes', value: '1.457 · 1.286 backend (com PostgreSQL real, executados também em modo globalization-invariant) e 171 frontend' },
            { label: 'Segurança', value: '50 testes em suíte própria e pentest em produção: 10 categorias, nenhuma vulnerabilidade' },
            { label: 'Rotas', value: '85, das quais 4 anônimas, cada uma com motivo escrito e travada por teste' },
        ],
        overview: [
            'Plataforma B2B de gestão, cálculo, conferência e auditoria de folha de pagamento brasileira, multiempresa. Departamentos pessoais e BPOs processam folha para muitas empresas, sob regras que mudam com o tempo, e precisam explicar cada valor, às vezes anos depois.',
            'O Prisma RH produz o número <strong>e a conta que levou até ele</strong>: quais rubricas entraram, sobre qual base, com qual parâmetro vigente. Calcula folha mensal, férias, rescisão, adiantamento de 13º e 13º anual, com INSS progressivo, FGTS e IRRF, além de um motor de conferência com workflow de tratamento e trilha de auditoria.',
        ],
        architecture: {
            summary: 'Monólito modular em ASP.NET Core (Minimal APIs) numa Lambda Function URL, com PostgreSQL no Neon e frontend React na Vercel. Importações pesadas seguem por SQS para um Lambda worker. Monólito e não microserviços: um produto com um banco e um time não tem o problema que microserviço resolve.',
            layers: [
                { name: 'PrismaRH.Dominio', desc: 'Regras de folha, sem EF Core, ASP.NET nem AWS.' },
                { name: 'PrismaRH.Aplicacao', desc: 'Casos de uso.' },
                { name: 'PrismaRH.Infraestrutura', desc: 'EF Core, integrações externas e camada de IA.' },
                { name: 'PrismaRH.Api', desc: 'Rotas, políticas de autorização e limites (a política padrão nega).' },
                { name: 'Lambda worker', desc: 'Processa importações pela fila SQS, com idempotência, retentativa com teto e DLQ.' },
            ],
        },
        flow: {
            title: 'Da importação ao holerite auditado',
            steps: [
                'O DP importa funcionários por CSV ou XLSX; a API valida, mostra o preview e o relatório de erros e processa na hora ou por fila (SQS + Lambda).',
                'O motor determinístico calcula a folha: cada tipo apura suas bases separadamente (INSS, FGTS e IRRF não incidem sobre o mesmo número) com os parâmetros vigentes na data.',
                'Cada holerite guarda a <strong>memória de cálculo</strong> linha a linha e congela os valores: alterar uma rubrica depois não reescreve a folha anterior.',
                'O motor de conferência aplica regras versionadas, com tolerância por organização, e abre inconsistências.',
                'O analista trata cada inconsistência (Detectada, Em análise, Justificada, Corrigida, Resolvida), com responsável, comentários e evidências.',
                'Cada alteração deixa rastro numa trilha somente-inserção: quem, o quê, quando e de quanto para quanto.',
            ],
        },
        highlights: [
            '<strong>Folha brasileira completa:</strong> mensal, férias, rescisão, adiantamento e 13º anual, com INSS progressivo, FGTS, IRRF com dependentes e o redutor da Lei 15.270/2025.',
            '<strong>Memória de cálculo persistida:</strong> cada passo, com a conta escrita, o teto aplicado e o arredondamento declarado (AwayFromZero, não o banker\'s rounding do .NET).',
            '<strong>Vigência sem sobreposição:</strong> exclusion constraint no PostgreSQL protege o histórico contratual, mesmo com requisições simultâneas.',
            '<strong>Multiempresa por filtro global do EF Core:</strong> recurso de outra organização devolve 404, não 403; a trilha de auditoria é somente-inserção.',
            '<strong>Importação CSV/XLSX:</strong> preview, validação e relatório de erros, síncrona ou por fila.',
            '<strong>IA que explica, não calcula:</strong> o modelo propõe filtro em vocabulário fechado e a aplicação valida; não existe SQL vindo do modelo nem valor financeiro que tenha origem nele.',
            '<strong>Defesa de SSRF:</strong> allowlist fixa em código, DNS resolvido com todos os IPs conferidos e redirect revalidado a cada salto.',
        ],
        limits: [
            'Não é homologado: nenhuma obrigação é transmitida a órgão público, e o produto não substitui um sistema comercial de folha.',
            'Afastamentos não existem no domínio, por isso a redução de férias por faltas (art. 130) não é aplicada.',
            'Três dos oito motivos de rescisão ficam bloqueados por falta de fonte oficial confiável; o sistema diz isso em vez de chutar.',
            'O motor carrega todos os contratos da empresa para processar uma folha: dezenas de milhares de vínculos exigiriam processar em lotes.',
            'O restore do banco foi testado uma vez, em 01/09/2026, e não é automatizado.',
            'A IA é uma camada de leitura: nenhum caminho iniciado por resposta de modelo escreve no banco.',
        ],
    },

    // ===== Demais projetos =====
    {
        slug: 'smartfinance',
        title: 'SmartFinance',
        subtitle: 'Plataforma de gestão financeira pessoal',
        image: '../assets/smartfinance_mockup.jpg',
        repo: 'https://github.com/Lucasantunesribeiro/smart_finance',
        demo: null, // fora do ar (testado em 2026-09-29)
        tags: ['.NET 8', 'C#', 'Next.js', 'TypeScript', 'PostgreSQL', 'RabbitMQ', 'SignalR', 'Terraform', 'AWS'],
        facts: [
            { label: 'Arquitetura', value: 'Modular monolith em camadas' },
            { label: 'Mensageria', value: 'RabbitMQ + Outbox Pattern' },
            { label: 'Testes', value: '81 testes .NET + 95 do microserviço' },
            { label: 'Infra', value: 'Terraform · ECS Fargate · RDS' },
        ],
        overview: [
            'Plataforma fullstack de gestão financeira pessoal, com autenticação segura, controle de contas, transações, categorias, orçamentos e analytics. O domínio central é o de gestão financeira, com frontend Next.js e backend .NET 8.',
            'O sistema centraliza a vida financeira do usuário em uma aplicação única, com segregação de dados por usuário, visão consolidada de saldo, controle de receitas e despesas, acompanhamento de orçamento e relatórios analíticos. Além do backend principal em .NET, o repositório mantém um microserviço complementar em Node.js/TypeScript voltado a pagamentos.',
        ],
        architecture: {
            summary: 'Backend principal em .NET 8 organizado como monólito modular em camadas, frontend desacoplado em Next.js 14 e um microserviço complementar em Node.js para pagamentos. A comunicação assíncrona interna acontece via Outbox + RabbitMQ.',
            layers: [
                { name: 'SmartFinance.Domain', desc: 'Entidades, enums e contratos de repositório e unidade de trabalho.' },
                { name: 'SmartFinance.Application', desc: 'Commands, queries, DTOs e interfaces de aplicação.' },
                { name: 'SmartFinance.Infrastructure', desc: 'EF Core, DbContext, migrations, repositórios genéricos e serviços.' },
                { name: 'SmartFinance.WebApi', desc: 'Controllers, middlewares, autenticação, mensageria, SignalR e bootstrap.' },
            ],
        },
        flow: {
            title: 'Fluxo de criação de uma transação',
            steps: [
                'O usuário autentica em <code>/api/v1/auth/login</code>; o backend valida a senha com PBKDF2, gera access token JWT e refresh token e devolve a sessão em cookies HttpOnly.',
                'O frontend passa a enviar o token CSRF nas operações mutáveis e consulta contas, categorias, transações, orçamentos e analytics.',
                'Ao criar uma transação, o handler valida a conta do usuário, grava a transação, atualiza o saldo e persiste uma mensagem na <strong>outbox</strong> — tudo na mesma transação de banco.',
                'O <code>OutboxPublisherService</code> lê a outbox e publica o evento no RabbitMQ.',
                'O <code>TransactionCreatedConsumerService</code> consome o evento, verifica idempotência em <code>ProcessedIntegrationEvents</code> e dispara notificação em tempo real via SignalR.',
                'O dashboard do usuário reflete a atualização sem precisar recarregar a página.',
            ],
        },
        highlights: [
            'Uso real de RabbitMQ com Outbox Pattern, retry, dead-letter queue e idempotência no consumo.',
            'Autenticação bem acima da média: JWT, rotação de refresh token, cookies HttpOnly, CSRF e rate limiting.',
            'Observabilidade com Serilog, Prometheus, OpenTelemetry, Grafana e CloudWatch.',
            'Atualização em tempo real via SignalR.',
            'Infraestrutura em Terraform: ECS Fargate, RDS, ALB, WAF, Secrets Manager, CloudTrail e IAM via OIDC do GitHub.',
        ],
        limits: [
            'O domínio ainda é predominantemente anêmico: a maior parte das regras vive em handlers e services, não em agregados ricos com value objects e domain events.',
            'A arquitetura é consistente em alto nível, mas não uniforme: Auth e Transactions usam MediatR com commands/queries, enquanto Accounts, Categories, Budgets e Analytics seguem por interfaces de serviço.',
            'O fluxo orientado a eventos está concentrado no evento de criação de transação — ainda não é uma malha ampla de eventos entre múltiplos contextos.',
            'O microserviço de pagamentos funciona como contexto complementar, e não como parte plenamente integrada ao produto principal.',
        ],
    },

    {
        slug: 'tenantcore',
        title: 'TenantCore',
        subtitle: 'Plataforma SaaS B2B multi-tenant',
        image: '../assets/tenant_core_mockup.jpg',
        repo: 'https://github.com/Lucasantunesribeiro/tenant_core',
        demo: 'https://purple-dune-018763b0f.4.azurestaticapps.net',
        tags: ['.NET 9', 'C#', 'MediatR', 'EF Core', 'SQL Server', 'Dapper', 'Redis', 'Quartz', 'React 18', 'Azure'],
        facts: [
            { label: 'Arquitetura', value: 'Monólito modular + Clean Architecture' },
            { label: 'Isolamento', value: 'Query filters globais por tenant' },
            { label: 'Testes', value: '33 testes (25 unitários, 8 de integração)' },
            { label: 'Infra', value: 'Azure App Service · Static Web Apps' },
        ],
        overview: [
            'Sistema fullstack para operação de um SaaS B2B multi-tenant. O domínio central é a gestão de workspaces empresariais compartilhados por múltiplas empresas, com isolamento por tenant, controle de usuários e perfis, cadastro de clientes, projetos e tarefas, assinatura por plano, limites de uso e auditoria.',
            'O problema resolvido não é apenas CRUD: o sistema simula um backend corporativo em que várias empresas usam a mesma plataforma sem vazar dados entre si, mantendo segurança, governança e visibilidade operacional.',
        ],
        architecture: {
            summary: 'Monólito modular com Clean Architecture dentro de um monorepo fullstack. A escolha entrega complexidade enterprise sem o custo operacional de uma malha de serviços.',
            layers: [
                { name: 'TenantCore.Api', desc: 'Borda HTTP: controllers, middlewares, auth, rate limit, health checks e Swagger.' },
                { name: 'TenantCore.Application', desc: 'Casos de uso, handlers do MediatR, validação com FluentValidation e contratos.' },
                { name: 'TenantCore.Domain', desc: 'Entidades com comportamento (UpdateSettings, ChangeRole, ChangePlan, Rotate) e enums.' },
                { name: 'TenantCore.Infrastructure', desc: 'EF Core, SQL Server, Redis, Quartz, JWT, password hashing e observabilidade.' },
            ],
        },
        flow: {
            title: 'Fluxo de autenticação e isolamento por tenant',
            steps: [
                'O usuário informa email, senha e <code>TenantId</code> na tela de login.',
                'O frontend envia o header <code>X-Tenant-Id</code> junto das credenciais para <code>/api/auth/login</code>.',
                'O middleware valida o tenant, busca o usuário dentro do tenant correto e valida a senha.',
                'O handler gera access token JWT e refresh token, salva o <em>hash</em> do refresh token no banco e grava auditoria de login.',
                'Em toda requisição seguinte, o middleware compara o header <code>X-Tenant-Id</code> com o claim <code>tenantId</code> do token.',
                'O <code>TenantCoreDbContext</code> aplica <strong>query filters globais</strong> por <code>TenantId</code> — consultas normais não conseguem enxergar dados de outro tenant.',
                'Operações de escrita checam permissão por papel, validam limites do plano, gravam <code>AuditLog</code> e invalidam caches como <code>usage:{tenantId}</code>.',
                'Jobs Quartz atualizam snapshots de uso, recalculam o estado de cota e limpam tokens expirados.',
            ],
        },
        highlights: [
            'Multi-tenancy com defesa em profundidade: middleware, claims do token e query filters do EF Core.',
            'JWT com refresh token rotativo e revogação, acima da média de projetos júnior.',
            'RBAC real por papel (Admin/Manager/User) com enforcement no backend.',
            'CQRS pragmático: MediatR para comandos e queries, e um read model com Dapper para o dashboard agregado.',
            'Observabilidade com Serilog, OpenTelemetry, health checks e Jaeger local.',
            'CI/CD e deploy real na Azure, com documentação de arquitetura, segurança, runbook e ADRs.',
        ],
        limits: [
            'Não há arquitetura orientada a eventos: sem broker, filas, consumidores, outbox ou sagas. O que existe é trilha de auditoria e processamento agendado.',
            'O DDD é parcial — as entidades têm comportamento, mas não há value objects, domain events, aggregate roots explícitos ou bounded contexts formais.',
            'É um monólito modular, não microservices: uma única API e um único banco relacional.',
            'O README principal menciona Neon PostgreSQL, mas o código atual está acoplado a SQL Server.',
        ],
    },

    {
        slug: 'linkguardiao',
        title: 'LinkGuardião',
        subtitle: 'Encurtador de URLs com controle de acesso',
        image: '../assets/linkguardiao_mockup.jpg',
        repo: 'https://github.com/Lucasantunesribeiro/LinkGuardiao',
        demo: 'https://linkguardiao.pages.dev/',
        tags: ['.NET 8', 'C#', 'React', 'TypeScript', 'DynamoDB', 'PostgreSQL', 'SQS', 'Lambda', 'AWS CDK'],
        facts: [
            { label: 'Arquitetura', value: 'Monólito modular + consumer assíncrono' },
            { label: 'Persistência', value: 'DynamoDB ou PostgreSQL (intercambiável)' },
            { label: 'Assíncrono', value: 'SQS + Lambda com retry e DLQ' },
            { label: 'Infra', value: 'AWS CDK · API Gateway · WAF' },
        ],
        overview: [
            'Sistema de encurtamento de URLs com autenticação, links protegidos por senha, expiração configurável e analytics de acesso processado de forma assíncrona.',
            'O problema é mais sofisticado do que um encurtador comum: controlar quem acessa um link, por quanto tempo ele permanece válido e como esse acesso é monitorado <strong>sem degradar a latência do redirecionamento</strong>.',
        ],
        architecture: {
            summary: 'Backend em camadas com um componente assíncrono separado para analytics via SQS + Lambda. A decisão evita complexidade prematura e aplica arquitetura distribuída só onde ela paga.',
            layers: [
                { name: 'LinkGuardiao.Api', desc: 'Composição da aplicação, controllers, middlewares, health checks e integração com AWS Lambda.' },
                { name: 'LinkGuardiao.Application', desc: 'DTOs, entidades, contratos, validações, serviços de aplicação e métricas.' },
                { name: 'LinkGuardiao.Infrastructure', desc: 'Implementações para DynamoDB, SQS, Redis, JWT e segurança.' },
                { name: 'LinkGuardiao.Infrastructure.PostgreSQL', desc: 'Implementação alternativa de persistência relacional com EF Core.' },
                { name: 'LinkGuardiao.AnalyticsConsumer', desc: 'Consumer dedicado para a fila de analytics.' },
            ],
        },
        flow: {
            title: 'Fluxo de redirecionamento e analytics',
            steps: [
                'O usuário autenticado cria um link; a API valida a URL, verifica o limite diário, aplica hash na senha (se houver) e persiste no storage configurado.',
                'Alguém acessa o link curto e o backend resolve o destino.',
                'Se o link for protegido, a UI consulta o endpoint público para saber se existe senha e solicita um <em>access grant</em> temporário.',
                'O redirect oficial valida o grant, <strong>enfileira a mensagem de analytics no SQS</strong> e responde imediatamente com o redirecionamento.',
                'A Lambda consumer processa a mensagem fora do caminho crítico, grava o acesso e incrementa o contador de cliques.',
                'O dashboard consulta as estatísticas agregadas e exibe cliques por data, navegador e top IPs.',
            ],
        },
        highlights: [
            'Decisão arquitetural correta de tirar o analytics do fluxo síncrono de redirect — troca consciente de consistência forte por latência.',
            'Suporte a dois modelos de persistência (DynamoDB e PostgreSQL), mostrando abstração real de storage.',
            'Mensageria real com SQS e Lambda consumer, incluindo retry e DLQ.',
            'Infraestrutura como código em CDK, incluindo WAF, alarmes e dashboard.',
            'Segurança acima da média: rate limiting, JWT com issuer/audience, PBKDF2, CORS restrito, security headers e access grant temporário.',
            'Testes automatizados distribuídos entre Application, API e persistência PostgreSQL.',
        ],
        limits: [
            'Não existe uma camada Domain separada da Application — as entidades são modelos anêmicos, sem comportamento rico.',
            'Sem aggregates, value objects, domain events explícitos ou bounded contexts formalizados.',
            'O uso de Event Driven é pontual (apenas o pipeline de analytics), não sistêmico.',
            'O analytics é eventualmente consistente: as estatísticas podem aparecer alguns instantes depois do clique.',
        ],
    },

    {
        slug: 'billing-ledger',
        title: 'BillingLedger',
        subtitle: 'Cobrança, pagamentos e conciliação em ledger',
        image: '../assets/billing_ledger_mockup.webp',
        repo: 'https://github.com/Lucasantunesribeiro/billing_ledger',
        demo: null,
        tags: ['.NET 9', 'C#', 'MassTransit', 'SQS/SNS', 'PostgreSQL', 'EF Core', 'AWS CDK', 'Serilog'],
        facts: [
            { label: 'Arquitetura', value: 'Distribuída orientada a eventos' },
            { label: 'Contextos', value: 'billing · payments · ledger (schemas separados)' },
            { label: 'Testes', value: '39/39 testes de domínio no Billing' },
            { label: 'Infra', value: 'AWS CDK · ECS Fargate · SNS/SQS + DLQ' },
        ],
        overview: [
            'Sistema backend para emissão de cobranças, recebimento de pagamentos e conciliação em ledger. Modela o ciclo de vida de uma fatura (<code>Draft → Issued → Paid/Cancelled/Overdue</code>), recebe notificações externas de pagamento via webhook, processa o evento de forma assíncrona e registra os efeitos financeiros em um livro-caixa imutável.',
            'O problema é típico de ambientes financeiros: separar as responsabilidades de faturamento, pagamento e contabilização <strong>sem acoplar tudo em uma única transação síncrona</strong>.',
        ],
        architecture: {
            summary: 'Não é microservices puro nem monólito simples. A classificação precisa é: sistema distribuído orientado a eventos, em monorepo com bounded contexts separados e banco físico compartilhado com schemas isolados por contexto.',
            layers: [
                { name: 'Billing.Api', desc: 'API pública e contexto de faturamento. Aggregate root Invoice com regras encapsuladas.' },
                { name: 'Payments.Worker', desc: 'Processamento de pagamentos com idempotência por (Provider, ExternalPaymentId).' },
                { name: 'Ledger.Worker', desc: 'Materialização contábil: lançamentos de débito e crédito.' },
                { name: 'Contracts', desc: 'Contratos de integração versionados (V1) com EventId, CorrelationId e SchemaVersion.' },
                { name: 'SharedKernel / BuildingBlocks', desc: 'Primitivas, eventos de domínio e abstrações técnicas compartilhadas.' },
            ],
        },
        flow: {
            title: 'Fluxo de emissão, pagamento e conciliação',
            steps: [
                'Um usuário autenticado cria uma invoice pela API; o aggregate nasce em <code>Draft</code> e um <code>AuditLog</code> é gravado.',
                'Ao emitir, a invoice muda para <code>Issued</code> e gera <code>InvoiceIssuedDomainEvent</code>.',
                'Um interceptor do EF Core converte o evento de domínio em uma linha na tabela <code>infra.outbox_messages</code> — na mesma transação da mudança de estado.',
                'O <code>OutboxDispatcherService</code> publica o contrato <code>InvoiceIssuedV1</code>.',
                'O <code>Ledger.Worker</code> consome o evento e cria um lançamento de <strong>débito</strong>.',
                'O provedor externo chama <code>POST /api/payments/webhook</code>; a API valida a assinatura <strong>HMAC-SHA256</strong> e publica <code>PaymentReceivedV1</code>.',
                'O <code>Payments.Worker</code> grava o <code>PaymentAttempt</code> com idempotência e publica <code>PaymentConfirmedV1</code>.',
                'O Billing marca a invoice como <code>Paid</code> e emite <code>InvoicePaidV1</code>; o Ledger cria o lançamento de <strong>crédito</strong> e o saldo da invoice tende a zero.',
            ],
        },
        highlights: [
            'Domínio bem representado: aggregate <code>Invoice</code>, regras de transição, domain events e <code>Money</code> como value object.',
            'Mensageria real na AWS com MassTransit sobre SQS/SNS.',
            'Outbox implementado exatamente no ponto mais sensível: a mudança de estado da invoice.',
            'Idempotência consciente, com índices únicos e guards nos consumers.',
            'Infraestrutura como código em CDK: VPC, RDS, Redis, ECS, ECR, SNS/SQS, DLQ e CloudWatch.',
            'Segurança baseline sólida: JWT + RBAC, webhook com HMAC, rate limiting, correlation id validado e segredos no Secrets Manager.',
        ],
        limits: [
            'A arquitetura é <em>layered + DDD-inspired</em>, não Clean Architecture rigorosa: a Billing.Api concentra tudo no mesmo assembly e os controllers chamam repositórios diretamente.',
            'As pastas <code>Application/Handlers</code> existem, mas estão vazias — não há pipeline formal de casos de uso com MediatR.',
            'A transição <code>Overdue</code> e o contrato <code>InvoiceOverdueV1</code> existem no domínio, mas não há job agendado nem consumer correspondente implementado.',
            'Parte da arquitetura está mais madura no desenho do que na execução completa.',
        ],
    },

    {
        slug: 'emissao-nfe',
        title: 'Emissão de NF-e e Controle de Estoque',
        subtitle: 'Sistema distribuído serverless orientado a eventos',
        image: '../assets/nfe_estoque_mockup.jpg',
        repo: 'https://github.com/Lucasantunesribeiro/emissao_nfe',
        demo: null, // fora do ar (testado em 2026-09-29)
        tags: ['.NET 8', 'C#', 'Go', 'Angular', 'DynamoDB', 'EventBridge', 'SQS', 'Lambda', 'AWS CDK', 'Cognito'],
        facts: [
            { label: 'Arquitetura', value: 'Serverless distribuída, event-driven' },
            { label: 'Runtimes', value: '.NET 8 (estoque) + Go (faturamento e PDF)' },
            { label: 'Persistência', value: 'DynamoDB single-table + GSIs' },
            { label: 'Infra', value: 'AWS CDK · API Gateway · X-Ray' },
        ],
        overview: [
            'Sistema distribuído de faturamento interno inspirado no domínio de emissão de NF-e. Cobre cadastro de produtos, criação e fechamento de notas, reserva assíncrona de estoque e geração de PDF após a solicitação de impressão.',
            '<strong>Importante:</strong> este projeto não é um emissor fiscal oficial. Não há integração com a SEFAZ, XML fiscal oficial, certificado A1/A3 ou regras tributárias reais. O domínio correto é "faturamento interno inspirado em NF-e" — o foco é arquitetura, integração assíncrona, cloud e qualidade de engenharia.',
        ],
        architecture: {
            summary: 'Sistema distribuído serverless com contextos de faturamento e estoque, inspirado em microservices e event-driven architecture, mas com persistência compartilhada no DynamoDB.',
            layers: [
                { name: 'servico-estoque (.NET 8)', desc: 'Clean Architecture enxuta: Api, Aplicacao, Dominio e Infraestrutura. Entidade Produto com DebitarEstoque().' },
                { name: 'servico-faturamento (Go)', desc: 'Lambdas de faturamento e geração de PDF. Entidade NotaFiscal com Fechar().' },
                { name: 'web-app (Angular)', desc: 'Frontend integrado ao Cognito, propagando JWT e X-Correlation-Id.' },
                { name: 'infra/cdk', desc: 'EventBridge, SQS, DLQ, DynamoDB, CloudFront, alarmes, dashboard e X-Ray.' },
            ],
        },
        flow: {
            title: 'Fluxo de fechamento de nota e reserva de estoque',
            steps: [
                'O usuário autentica via Cognito no frontend Angular, que passa a enviar JWT e <code>X-Correlation-Id</code>.',
                'O usuário cadastra produtos no serviço de estoque (.NET) e cria uma nota no serviço de faturamento (Go).',
                'Ao fechar a nota, o faturamento atualiza o status e grava o evento <code>Faturamento.NotaFechada</code> usando <code>TransactWriteItems</code> — nota e evento na mesma transação.',
                'Uma regra do EventBridge encaminha o evento para a fila SQS de reserva.',
                'O consumer de estoque em Go lê a nota, reserva saldo no DynamoDB e publica <code>ReservaConfirmada</code> ou <code>ReservaFalhou</code>.',
                'O faturamento consome a confirmação e atualiza a nota para <code>RESERVADA</code> ou <code>CANCELADA</code>.',
                'Na impressão, a API exige <code>Idempotency-Key</code>; a Lambda de PDF gera o arquivo, salva no S3 e a solicitação passa para <code>CONCLUIDA</code>.',
            ],
        },
        highlights: [
            'Event-driven implementado de verdade: EventBridge, SQS e DLQ provisionados no CDK e usados em código executável.',
            'Outbox publisher em .NET usando DynamoDB Streams — um diferencial técnico incomum.',
            'DynamoDB com single-table design e GSIs, raro em portfólios júnior.',
            'Propagação de correlation-id entre frontend, APIs e eventos.',
            'Observabilidade provisionada: logs estruturados, alarmes, dashboard e X-Ray.',
            'Sistema poliglota, com o serviço .NET demonstrando Clean Architecture aplicada.',
        ],
        limits: [
            'Estoque e faturamento compartilham a mesma tabela principal no DynamoDB, o que reduz a autonomia dos contextos — não são microservices puros.',
            'A atomicidade do outbox não é uniforme: <code>FecharNota()</code> usa transação, mas <code>CriarSolicitacaoImpressao()</code> e <code>ReservarEstoqueHandler</code> gravam em operações separadas.',
            'O CDK ainda instancia uma <code>NetworkStack</code> com VPC e recursos pensados para ECS/RDS, herdados de uma arquitetura anterior, mesmo com as Lambdas rodando fora da VPC.',
            'Convivem artefatos da trilha ativa serverless e de uma fase antiga com PostgreSQL, RabbitMQ e Docker Compose, o que reduz a clareza do repositório.',
        ],
    },

    {
        slug: 'collabdocs',
        title: 'CollabDocs',
        subtitle: 'Documentos colaborativos em tempo real',
        image: '../assets/collabdocs_mockup.jpg',
        repo: 'https://github.com/Lucasantunesribeiro/Collabdocs',
        demo: 'https://collabdocs-app.vercel.app/',
        tags: ['.NET 9', 'C#', 'MediatR', 'Next.js', 'PostgreSQL', 'Redis', 'RabbitMQ', 'Cloudflare Workers', 'Testcontainers'],
        facts: [
            { label: 'Arquitetura', value: 'Contextos distribuídos (.NET + edge)' },
            { label: 'Padrão', value: 'Clean Architecture + CQRS com MediatR' },
            { label: 'Tempo real', value: 'WebSocket + Durable Objects' },
            { label: 'Testes', value: 'Integração com Testcontainers' },
        ],
        overview: [
            'Plataforma de documentos colaborativos com autenticação OAuth, controle de visibilidade, gestão de colaboradores e edição em tempo real. Resolve um problema típico de produto SaaS: permitir que múltiplos usuários criem, compartilhem e editem documentos com regras de acesso e sincronização entre clientes.',
            'O sistema tem três frentes: gerenciamento de documentos (CRUD, versionamento e compartilhamento), colaboração em tempo real (presença e broadcast via WebSocket) e autenticação com login via GitHub/Google.',
        ],
        architecture: {
            summary: 'Aplicação distribuída por contextos, com backend principal em .NET (monólito modular em camadas) e um contexto edge separado, na Cloudflare, dedicado à colaboração em tempo real.',
            layers: [
                { name: 'CollabDocs.Domain', desc: 'Entidades, enums, eventos e interfaces. Regras explícitas como Document.CanEdit() e CanView().' },
                { name: 'CollabDocs.Application', desc: 'Commands, queries, DTOs e handlers (CreateDocumentHandler, UpdateDocumentHandler...).' },
                { name: 'CollabDocs.Infrastructure', desc: 'EF Core, repositórios, cache Redis, mensageria RabbitMQ e outbox.' },
                { name: 'CollabDocs.API', desc: 'Controllers finos, autenticação JWT, Swagger, DI e observabilidade.' },
                { name: 'workers/ (Cloudflare)', desc: 'Runtime edge: WebSocket, Durable Objects, rate limiting e integrações.' },
            ],
        },
        flow: {
            title: 'Fluxo de escrita e colaboração em tempo real',
            steps: [
                'O usuário faz login via GitHub ou Google no NextAuth; é gerada uma sessão JWT HS256 compartilhada entre frontend, Worker e .NET.',
                'O cliente chama <code>/api/dotnet/[...path]</code> no Next.js, que faz proxy server-side para a API .NET.',
                'A API valida o JWT, resolve o usuário via claims e executa o caso de uso através do MediatR.',
                'O handler aplica a regra de negócio, persiste no PostgreSQL e, quando aplicável, grava uma mensagem na outbox.',
                'Após a escrita, o backend invalida o cache Redis do usuário.',
                'No editor, o cliente abre um WebSocket para o Worker da Cloudflare — o JWT vai por query string, porque o browser não permite header customizado no upgrade do WebSocket.',
                'O Worker valida o token, consulta a permissão e encaminha a sessão a um <strong>Durable Object por documento</strong>, que mantém os usuários conectados e faz o broadcast das atualizações.',
            ],
        },
        highlights: [
            'CQRS com MediatR aplicado de forma real e visível: commands e queries com handlers dedicados por caso de uso.',
            'Uso real de RabbitMQ e Transactional Outbox, raro em portfólios júnior.',
            'Regras de autorização encapsuladas na entidade de domínio, não espalhadas em controllers.',
            'Colaboração em tempo real com Cloudflare Workers e Durable Objects.',
            'Deploy multi-cloud: Vercel, Cloudflare e AWS, com CI/CD no GitHub Actions e OIDC.',
            'Testes .NET fortes para nível de portfólio, incluindo integração com Testcontainers.',
        ],
        limits: [
            'O principal débito estrutural é a <strong>divisão de fonte de verdade</strong>: o frontend usa .NET + PostgreSQL para documentos, enquanto o Worker mantém lógica equivalente no D1 e autoriza o WebSocket consultando o D1, não o PostgreSQL.',
            'O consumer de eventos hoje apenas registra logs — não materializa projeções nem sincroniza contextos.',
            'O DDD é tático e parcial: faltam aggregates ricos, value objects e bounded contexts formalizados.',
            'A arquitetura está em transição: o desenho é interessante, mas a consistência entre contextos ainda não está consolidada.',
        ],
    },

    {
        slug: 'pedidos-event-sourcing',
        title: 'Gestão de Pedidos Distribuído',
        subtitle: 'Pedidos, estoque e pagamento com outbox e compensação',
        image: '../assets/sistema_pedidos_distribuido_mockup.jpg',
        repo: 'https://github.com/Lucasantunesribeiro/Sistema_de_Gestao_de_Pedidos_Distribu-do_com_Event_Sourcing',
        demo: null,
        tags: ['Java', 'Spring Boot', 'PostgreSQL', 'RabbitMQ', 'Outbox', 'Docker', 'JWT'],
        facts: [
            { label: 'Arquitetura', value: 'Monólito modular por domínio' },
            { label: 'Mensageria', value: 'Outbox + RabbitMQ' },
            { label: 'Testes', value: '217 testes · 63,3% de cobertura de linhas' },
            { label: 'Extras', value: 'Testes E2E e teste de carga' },
        ],
        overview: [
            'Sistema de gestão de pedidos que cobre todo o ciclo operacional: autenticação, criação do pedido, reserva de estoque, processamento de pagamento, confirmação/cancelamento, painel operacional e trilha de eventos.',
            'O problema resolvido é o típico de plataformas transacionais: evitar venda sem estoque, manter o fluxo de pagamento integrado ao pedido, reduzir acoplamento entre módulos e dar visibilidade operacional.',
            '<strong>Nota de honestidade arquitetural:</strong> apesar do nome do repositório sugerir Event Sourcing e microservices, o runtime ativo hoje está consolidado em um monólito modular bem estruturado. Isso não diminui o projeto — apenas muda a forma correta de apresentá-lo.',
        ],
        architecture: {
            summary: 'Monólito modular por domínio, com módulos separados e comunicação assíncrona via outbox → RabbitMQ. O núcleo ativo foi consolidado a partir de uma fase anterior mais fragmentada.',
            layers: [
                { name: 'order', desc: 'Casos de uso do pedido (CreateOrderUseCase, CancelOrderUseCase) e OrderBusinessRules.' },
                { name: 'inventory', desc: 'Reserva e liberação de estoque, com locking otimista e pessimista.' },
                { name: 'payment', desc: 'Processamento de cobrança via gateway HTTP ou sandbox local.' },
                { name: 'auth / websocket', desc: 'Autenticação JWT com RBAC e notificações em tempo real.' },
                { name: 'infrastructure', desc: 'EventPublisher, DomainEventEntity e DomainEventOutboxPublisher.' },
            ],
        },
        flow: {
            title: 'Fluxo de criação de pedido com compensação',
            steps: [
                'O usuário autentica e recebe um token JWT.',
                'O frontend chama a API de pedidos; o backend valida a requisição e executa o <code>CreateOrderUseCase</code>.',
                'O módulo de estoque verifica disponibilidade e <strong>cria uma reserva</strong> para evitar overselling.',
                'O módulo de pagamento processa a tentativa de cobrança via gateway ou sandbox.',
                'Se tudo der certo, o pedido é confirmado. Se estoque ou pagamento falharem, o fluxo executa <strong>compensação</strong> e atualiza o estado do pedido.',
                'Eventos de domínio são persistidos em tabela própria — não é <em>fire and forget</em> direto para o broker.',
                'Um publisher de outbox envia os eventos pendentes ao RabbitMQ.',
                'Um scheduler trata a expiração automática de reservas, evitando estoque preso indefinidamente.',
            ],
        },
        highlights: [
            'Domínio forte para mercado enterprise: pedidos, estoque e pagamento coordenados.',
            'Preocupação concreta com consistência e concorrência, incluindo locking otimista e pessimista no estoque.',
            'Uso real de mensageria com RabbitMQ e padrão Outbox.',
            'Segurança acima da média: JWT, RBAC, CORS, CSP, HSTS e rate limiting.',
            'Suíte de testes robusta: 217 testes sem falhas, 63,29% de cobertura de linhas via JaCoCo.',
            'Existência de testes E2E e teste de carga, incomum em portfólios.',
        ],
        limits: [
            'Não é um conjunto de microservices independentes ativos, apesar do nome do repositório.',
            'O Event Sourcing não é aplicado de forma completa no runtime atual — o que existe é outbox de eventos de domínio.',
            'A pasta <code>legacy/</code> mantém artefatos de uma fase anterior mais fragmentada, o que reduz a clareza do repositório.',
            'A cobertura de branches (40,84%) é bem menor que a de linhas.',
        ],
    },

    {
        slug: 'agente-sumarizacao',
        title: 'Agente de Sumarização AI',
        subtitle: 'Extração e resumo assíncrono de artigos',
        image: '../assets/article_summarizer_mockup.jpg',
        repo: 'https://github.com/Lucasantunesribeiro/article_summarizer_agent',
        demo: 'https://article-summarizer-agent.onrender.com/',
        tags: ['Python', 'Flask', 'Celery', 'RabbitMQ', 'SQLAlchemy', 'Google Gemini', 'React', 'TypeScript', 'Docker'],
        facts: [
            { label: 'Arquitetura', value: 'Monólito modular em camadas' },
            { label: 'Assíncrono', value: 'Celery + outbox relay para RabbitMQ' },
            { label: 'Testes', value: '75,78% de cobertura' },
            { label: 'Observabilidade', value: 'Prometheus · Grafana · OpenTelemetry' },
        ],
        overview: [
            'Plataforma fullstack para extração, processamento e sumarização assíncrona de artigos públicos na web. O sistema recebe uma URL, executa o scraping com proteções de segurança, processa o texto e gera um resumo — por método extrativo baseado em TF-IDF ou por integração com o Google Gemini.',
            'Oferece histórico, download dos artefatos em <code>txt</code>, <code>md</code> ou <code>json</code> e painel administrativo com estatísticas, limpeza de cache e rotação de segredo JWT.',
        ],
        architecture: {
            summary: 'Monólito modular com separação explícita de camadas, adequado para demonstrar organização de código sem assumir a complexidade operacional de microservices reais.',
            layers: [
                { name: 'presentation/', desc: 'Borda HTTP com Flask Blueprints para API, autenticação e entrega da SPA React.' },
                { name: 'application/', desc: 'Comandos, queries, handlers e um event bus de aplicação.' },
                { name: 'domain/', desc: 'Entidades (SummarizationTask, User, AuditLogEntry), eventos e contratos de repositório.' },
                { name: 'infrastructure/', desc: 'Repositórios SQLAlchemy, wiring de dependências, auth e pipeline runner.' },
                { name: 'modules/ e tasks/', desc: 'Scraper, sumarizador, cache, rate limiting, tracing — e execução assíncrona com Celery.' },
            ],
        },
        flow: {
            title: 'Fluxo de sumarização',
            steps: [
                'O usuário envia <code>POST /api/sumarizar</code> com a URL e os parâmetros de resumo.',
                'A API normaliza a URL, valida o formato, aplica rate limit e aceita um <code>X-Idempotency-Key</code> opcional.',
                'O handler cria a <code>SummarizationTask</code>, persiste e registra o evento <code>TaskSubmitted</code>.',
                'O <code>AsyncTaskDispatcher</code> despacha o processamento para o Celery; se o Celery estiver indisponível, cai para uma thread local.',
                'O pipeline executa scraping, <strong>proteção contra SSRF</strong>, limpeza de texto, detecção de idioma, sumarização e geração dos arquivos de saída.',
                'A tarefa é atualizada para <code>done</code> ou <code>failed</code>, métricas são publicadas e os eventos vão para a auditoria.',
                'O frontend faz polling em <code>GET /api/tarefa/&lt;task_id&gt;</code> até a conclusão.',
                'Em paralelo, um job periódico lê a tabela de outbox e publica os eventos pendentes no RabbitMQ.',
            ],
        },
        highlights: [
            'Mensageria real com RabbitMQ e Celery, com fallback para thread local quando o broker está fora.',
            'Outbox, idempotência e audit log — combinação rara em projetos pessoais.',
            'Segurança acima da média: proteção SSRF, JWT, CSRF, RBAC, rate limiting, security headers e rotação de segredo.',
            'Observabilidade completa: Prometheus, Grafana, OpenTelemetry, Jaeger e logs estruturados.',
            'Persistência versionada com SQLAlchemy e Alembic.',
            'Cobertura de testes de 75,78% na validação executada.',
        ],
        limits: [
            'O domínio é relativamente simples e anêmico — a maior regra de negócio explícita é a máquina de estados da tarefa.',
            'Não há bounded contexts claros, aggregates complexos ou linguagem ubíqua forte.',
            'O CQRS é organizacional: não existe segregação física de banco, read models especializados ou event sourcing.',
            'O event bus é interno e em memória — não é uma plataforma distribuída orientada a eventos de ponta a ponta.',
            'A demo está hospedada no plano gratuito do Render, então a primeira requisição pode levar cerca de 30 segundos (cold start).',
        ],
    },

    {
        slug: 'armazem-sao-joaquim',
        title: 'Armazém São Joaquim',
        subtitle: 'Plataforma digital para restaurante, pousada e café',
        image: '../assets/armazem_sao_joaquim_mockup.jpg',
        repo: 'https://github.com/Lucasantunesribeiro/armazemsaojoaquim',
        demo: 'https://armazemsaojoaquim.com.br/',
        badge: 'Cliente real · em produção',
        tags: ['Next.js', 'TypeScript', 'Supabase', 'PostgreSQL', 'RLS', 'Tailwind', 'i18n'],
        facts: [
            { label: 'Status', value: 'Em produção, em domínio próprio' },
            { label: 'Arquitetura', value: 'Monólito modular serverless' },
            { label: 'Banco', value: 'PostgreSQL com RLS e migrations' },
            { label: 'Idiomas', value: 'Rotas separadas para PT e EN' },
        ],
        overview: [
            'Plataforma digital fullstack para o Armazém São Joaquim, combinando site institucional, cardápio online, blog, área de pousada, catálogo do café, galeria de arte e um painel administrativo para operação do negócio.',
            'É o único projeto deste portfólio com <strong>cliente real e tráfego real</strong>. Em vez de uma landing page, o sistema centraliza exposição de produtos e conteúdo, autenticação, reservas, gestão administrativa e integrações de comunicação e analytics.',
        ],
        architecture: {
            summary: 'Monólito modular serverless sobre o App Router do Next.js, com Supabase como backend-as-a-service. A escolha prioriza velocidade de entrega para um cliente real em vez de rigor arquitetural.',
            layers: [
                { name: 'app/[locale]', desc: 'Páginas públicas e administrativas, com internacionalização por segmento de rota.' },
                { name: 'app/api', desc: 'Endpoints serverless (route handlers) públicos, administrativos e de diagnóstico.' },
                { name: 'components', desc: 'UI organizada em admin, atoms, molecules, sections e ui — inspiração em Atomic Design.' },
                { name: 'lib', desc: 'Autenticação, acesso ao Supabase, cache, retry, monitoramento e validações.' },
                { name: 'supabase/migrations', desc: 'Evolução do banco, políticas RLS, funções SQL e correções de segurança.' },
            ],
        },
        flow: {
            title: 'Fluxo de reserva',
            steps: [
                'O visitante acessa páginas públicas em <code>app/[locale]</code>, com conteúdo estático e conteúdo dinâmico vindo do Supabase.',
                'O usuário se autentica via Supabase Auth.',
                'Ao criar uma reserva, o frontend chama <code>/api/reservas</code>.',
                'A rota valida os dados, grava no banco e gera um token de confirmação.',
                'O usuário confirma a reserva via <code>/api/reservas/confirm?token=...</code>.',
                'O painel administrativo consome <code>/api/admin/*</code> para gerir blog, cardápio, usuários, reservas, pousada e galeria.',
                'O PostgreSQL, protegido por RLS em várias tabelas, sustenta os módulos operacionais.',
            ],
        },
        highlights: [
            'Escopo real de negócio, com cliente e domínio próprio — muito acima de projeto tutorial.',
            'Painel administrativo amplo, cobrindo múltiplos módulos operacionais.',
            'Internacionalização por rota (pt e en).',
            'PostgreSQL com migrations versionadas e Row Level Security.',
            'Build de produção funcionando em Next.js, com type-check passando.',
            'Deploy com headers e política de cache configurados.',
        ],
        limits: [
            'Não aplica Clean Architecture, DDD, CQRS nem Event Driven — as rotas falam diretamente com o Supabase e carregam a regra de negócio nelas mesmas.',
            'Existe <em>drift</em> arquitetural: convivem implementações antiga e nova para o mesmo domínio (por exemplo, contratos de blog em versão simples e multilíngue).',
            'A autorização depende mais de verificação procedural e do service role key do que de uma camada de autorização coesa.',
            'O escopo cresceu mais rápido que a disciplina arquitetural — é um projeto de produto, não uma vitrine de arquitetura.',
        ],
    },
];
